{
  flake.nixosModules.bin = { unstable, username, ... }:
    with unstable;
    let
      claudep = writeShellScriptBin "claudep" ''
        exec env CLAUDE_CONFIG_DIR="$HOME/.claudep" ${unstable.claude-code}/bin/claude "$@"
      '';
    in
    {
      home-manager.users.${username}.home.packages = [
        editorconfig-core-c
        bc
        jq
        gh
        helix
        gnutls
        binutils
        unzip
        fd
        (ripgrep.override { withPCRE2 = true; })
        texlive.combined.scheme-medium
        pandoc
        fzf
        bat
        socat
        coreutils
        wakatime-cli
        tldr
        cmake
        gcc
        python3
        tree-sitter
        lazygit
        cargo
        lua
        lua51Packages.luarocks-nix
        deno
        dasel
        prettierd
        stylua
        lsof
        openjdk
        sbt
        trashy
        koka
        nixd
        lua-language-server
        vtsls
        vscode-langservers-extracted
        yaml-language-server
        vscode-js-debug
        terraform-ls
        harper
        dockerfile-language-server
        purescript
        basedpyright
        ffmpeg
        yt-dlp
        ruff
        rust-analyzer
        unrar
        psmisc
        gnumake
        nix-tree
        claude-code
        claudep
        codex
        github-cli
        jj-fzf
        jjui
        piper
        corepack
        xsel
        wl-clipboard
        logseq
        wasmtime
        devenv
        aws-cdk-cli
        nordpass
      ];
    };
}
