# Kak-lsp
eval %sh{kak-lsp --kakoune -s $kak_session}
lsp-enable

# elm format-on-write
hook global WinSetOption filetype=elm %{
  set window formatcmd 'elm-format --stdin'

  hook buffer BufWritePre .* %{format}
} 

# Use system clipboard
hook global NormalKey y|d|c %{ nop %sh{
      printf %s "$kak_main_reg_dquote" | xsel --input --clipboard
}}
map global user P '!xsel --output --clipboard<ret>'
map global user p '<a-!>xsel --output --clipboard<ret>'

# Theme
colorscheme dracula
lsp-auto-hover-enable

# yy to escape
hook global InsertChar y %{ try %{
  exec -draft hH <a-k>yy<ret> d
  exec <esc>
}}

# Move on colemak
map -docstring "select to next word end" global normal 'j' 'e'
map -docstring "select to next WORD end" global normal '<a-j>' '<a-e>'
map -docstring "buffer end" global goto 'j' 'e'
map -docstring "extend to next word end" global normal 'J' 'E'
map -docstring "extend to next WORD end" global normal '<a-J>' '<a-E>'
map -docstring "move left" global normal 'n' 'h'
map -docstring "select to line begin" global normal '<a-n>' '<a-h>'
map -docstring "line begin" global goto 'n' 'h'
map -docstring "scroll left" global view 'n' 'h'
map -docstring "extend left" global normal 'N' 'H'
map -docstring "extend to line begin" global normal '<a-N>' '<a-H>'
map -docstring "insert before selected text" global normal 'h' 'i'
map -docstring "select inner object" global normal '<a-h>' '<a-i>'
map -docstring "jump forward in jump list" global normal '<c-h>' '<c-i>'
map -docstring "line begin (non blank)" global goto 'h' 'i'
map -docstring "insert at line begin" global normal 'H' 'I'
map -docstring "move down" global normal 'e' 'j'
map -docstring "join lines" global normal '<a-e>' '<a-j>'
map -docstring "buffer bottom" global goto 'e' 'j'
map -docstring "scroll down" global view 'e' 'j'
map -docstring "extend down" global normal 'E' 'J'
map -docstring "join lines and select spaces" global normal '<a-E>' '<a-J>'
map -docstring "move up" global normal 'i' 'k'
map -docstring "keep selections matching given regex" global normal '<a-i>' '<a-k>'
map -docstring "buffer top" global goto 'i' 'k'
map -docstring "scroll up" global view 'i' 'k'
map -docstring "extend up" global normal 'I' 'K'
map -docstring "keep selections not matching given regex" global normal '<a-I>' '<a-K>'
map -docstring "move right" global normal 'o' 'l'
map -docstring "select to line end" global normal '<a-o>' '<a-l>'
map -docstring "force screen redraw" global normal '<c-o>' '<c-l>'
map -docstring "line end" global goto 'o' 'l'
map -docstring "scroll right" global view 'o' 'l'
map -docstring "extend right" global normal 'O' 'L'
map -docstring "extend to line end" global normal '<a-O>' '<a-L>'
map -docstring "select next current search pattern match" global normal 'k' 'n'
map -docstring "select previous current search pattern match" global normal '<a-k>' '<a-n>'
map -docstring "extend with next current search pattern match" global normal 'K' 'N'
map -docstring "extend with previous current search pattern match" global normal '<a-K>' '<a-N>'
map -docstring "insert on new line below" global normal 'l' 'o'
map -docstring "add a new empty line below" global normal '<a-l>' '<a-o>'
map -docstring "jump backward in jump list" global normal '<c-l>' '<c-o>'
map -docstring "insert on new line above" global normal 'L' 'O'
map -docstring "add a new empty line above" global normal '<a-L>' '<a-O>'
