# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}:

{
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = [
    "xhci_pci"
    "ahci"
    "nvme"
    "usbhid"
    "usb_storage"
    "sd_mod"
  ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/12a56770-bf7f-4526-b5f1-520f3ecd555b";
    fsType = "ext4";
  };

  fileSystems."/media/mid" = {
    device = "/dev/disk/by-uuid/39c35311-3514-418b-a83b-0bc2fffb0a1d";
    fsType = "ext4";
  };

  fileSystems."/media/tiny" = {
    device = "/dev/disk/by-uuid/fe5647ae-b71a-4026-a2e9-54cbff322b25";
    fsType = "ext4";
  };

  fileSystems."/media/old_and_slow" = {
    device = "/dev/disk/by-uuid/A41A22F51A22C3E0";
    fsType = "ntfs";
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/665B-A1CC";
    fsType = "vfat";
    options = [
      "fmask=0077"
      "dmask=0077"
    ];
  };

  swapDevices = [
    { device = "/dev/disk/by-uuid/48ff442b-b818-4db4-b38c-1ca563e53e11"; }
  ];

  networking.useDHCP = lib.mkDefault true;
  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;

  hardware.keyboard.qmk.enable = true;

  # Nvidia stuff
  hardware.graphics.enable = true;
  services.xserver.videoDrivers = [ "nvidia" ];

  hardware.nvidia = {
    modesetting.enable = true;
    open = true;
    nvidiaSettings = true;
    powerManagement.enable = true;
  };
}
